const Images = {
  BG: require('../assets/images/bg.png'),
  BG_DARK: require('../assets/images/bg_dark.png'),
  DOC: require('../assets/images/doc.png'),
  BG_1: require('../assets/images/bg_1.png'),
  BG_2: require('../assets/images/bg_2.png'),
  BG_3: require('../assets/images/bg_3.png'),
  BG_4: require('../assets/images/bg_4.png'),
  BG_5: require('../assets/images/bg_5.png'),
  BG_6: require('../assets/images/bg_6.png'),
  WORK: require('../assets/images/work.png'),
  FEATURED_BG_IMAGE: require('../assets/images/featured_bg_image.png'),
  MOBILE_IMAGE: require('../assets/images/mobile_image.png'),
  PDF: require('../assets/images/pdf.png'),
  PROFILE: require('../assets/images/profile.png'),
  SKETCH: require('../assets/images/sketch.png'),
  START_LEARNING: require('../assets/images/start_learning.png'),
  STUDENT_1: require('../assets/images/student_1.png'),
  STUDENT_2: require('../assets/images/student_2.png'),
  STUDENT_3: require('../assets/images/student_3.png'),
  THUMBNAIL_1: require('../assets/images/thumbnail_1.png'),
  THUMBNAIL_2: require('../assets/images/thumbnail_2.png'),
  THUMBNAIL_3: require('../assets/images/thumbnail_3.png'),
  THUMBNAIL_4: require('../assets/images/thumbnail_4.png'),
  LEARNING: require('../assets/images/Learning.png'),
  SUCCESSIVE: require('../assets/images/successive.jpg'),
};
export {Images};
